### ISSUE TITLE
CommandView devtools errors

### ISSUE THREAD

**Issue by jessica-obrien** [beer-garden/react-ui#91]
When looking at the CommandView (Systems > Explore button > Execute button), there are two errors that come up in devtools. They both should be run to ground.

```
react_devtools_backend.js:4026 Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <WithStyles(ForwardRef(Select))>. See https://reactjs.org/link/warning-keys for more information.
    at WithStyles (http://10.114.20.228:4000/static/js/bundle.js:78767:31)
    at http://10.114.20.228:4000/static/js/bundle.js:34918:20
....
```

```
xhr.js:210          POST http://10.114.20.228:4000/api/v1/requests 400 (Bad Request)
```

beer-garden terminal output: 

```
2022-07-22 15:39:24,653 - tornado.application - ERROR - Uncaught exception POST /api/v1/requests (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:2337', method='POST', uri='/api/v1/requests', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/jlobri3/.pyenv/versions/beer-garden/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/jlobri3/dev/beer-garden/src/app/beer_garden/api/http/handlers/v1/request.py", line 478, in post
    serialize_kwargs={"to_string": False},
  File "/home/jlobri3/dev/beer-garden/src/app/beer_garden/api/http/client.py", line 20, in __call__
    result = await result
  File "/home/jlobri3/.pyenv/versions/3.7.13/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jlobri3/dev/beer-garden/src/app/beer_garden/requests.py", line 629, in process_request
    request = _validate_request(request)
  File "/home/jlobri3/dev/beer-garden/src/app/beer_garden/requests.py", line 593, in _validate_request
    return RequestValidator.instance().validate_request(request)
  File "/home/jlobri3/dev/beer-garden/src/app/beer_garden/requests.py", line 76, in validate_request
    system = self.get_and_validate_system(request)
  File "/home/jlobri3/dev/beer-garden/src/app/beer_garden/requests.py", line 115, in get_and_validate_system
    % (request.instance_name, system.name)
brewtils.errors.ModelValidationError: Could not find instance with name 'None' in system 'complex'
2022-07-22 15:39:24,655 - tornado.access - WARNING - 400 POST /api/v1/requests (127.0.0.1) 138.87ms
```

**Comment by jlrpnbbngtn** [comment]
This is handled in #61, closing.
